language: objective-c

branches:
 only:
 - master
 - develop

xcode_project: OpenPokeMap.xcodeproj
xcode_scheme: OpenPokeMap
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
- xcodebuild clean build test -project OpenPokeMap.xcodeproj -list
